### ISSUE TITLE
future::makeClusterPSOCK() has moved to parallelly::makeClusterPSOCK()

### ISSUE THREAD

**Issue by HenrikBengtsson** [xuyiqing/interflex#24]
`future::makeClusterPSOCK()` is a re-export of `parallelly::makeClusterPSOCK()` since 2020. It will eventually be removed from the **future** package.  Please update the following uses accordingly:

https://github.com/xuyiqing/interflex/blob/e35ba4a414721da1874caa6759cc33055494fa98/R/kernel.R#L767

https://github.com/xuyiqing/interflex/blob/e35ba4a414721da1874caa6759cc33055494fa98/R/kernel.R#L2123

https://github.com/xuyiqing/interflex/blob/e35ba4a414721da1874caa6759cc33055494fa98/R/linear.R#L1804

https://github.com/xuyiqing/interflex/blob/e35ba4a414721da1874caa6759cc33055494fa98/R/binning.R#L2338

**Comment by xuyiqing** [comment]
Fixed. thanks.

**Comment by HenrikBengtsson** [comment]
> Fixed. thanks.

I still see:

https://github.com/xuyiqing/interflex/blob/8c59a6cbf576fa3a67df3875866710b7ba129993/NAMESPACE#L14

**Comment by xuyiqing** [comment]
Good catch, Henrik — `importFrom("future","makeClusterPSOCK")` was a leftover; nothing in `R/` calls `makeClusterPSOCK` anymore. Removed on the `dev` branch. Also dropped the now-unused `importFrom("parallel", "detectCores", "stopCluster", "makeCluster")` line while I was there. Will be merged to `master` in the next update. Thanks!
